services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo_admin:password@mongo_db:27017
      - REDIS_URL=redis://redis_db:6379/0
    depends_on:
      - mongo_db
      - redis_db

  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library_db

  redis_db:
    image: redis:7-alpine
    restart: always

  prism:
    image: stoplight/prism:4
    command: mock /tmp/openapi.yaml --host 0.0.0.0 --port 4010
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml
    ports:
      - "4010:4010"