version: "3.8"

volumes:
  mongo_data:

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo_admin:password@mongo_db:27017
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library_db
    volumes:
      - mongo_data:/var/lib/mongodb/data
    ports:
      - "27017:27017"
